version: '{build}'
image: Visual Studio 2019

cache:
  - C:\Users\appveyor\.m2

install:
  - git submodule update --init --recursive

build_script:
  - set "PATH=C:\Program Files\Java\jdk11;%PATH%"
  - mvn verify -B -V -e

artifacts:
  - path: 'sonar-groovy-plugin\target\*.jar'

on_failure:
  - ps: Get-ChildItem *\target\surefire-reports\*.txt | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
